name: Publish release
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  run-ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
  run-e2e-tests:
    name: Run E2E tests
    needs: run-ci
    uses: ./.github/workflows/e2e.yml
  upload:
    name: Upload to partner blob container
    needs: [run-ci, run-e2e-tests]
    runs-on: ubuntu-22.04
    steps:
      - name: Install AzCopy
        run: |
          curl -sSL -O https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install azcopy
      - name: Download distributions
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: dists
          path: dist/
      - name: Get package version
        run: |
          azstoragetorch_version=$(ls dist/azstoragetorch-*.whl | head -n 1 | cut -d- -f2)
          test -n "$azstoragetorch_version"
          echo "AZSTORAGETORCH_VERSION=$azstoragetorch_version" >> "$GITHUB_ENV"
      - name: Azure login
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Upload distributions to blob container
        env:
          AZCOPY_AUTO_LOGIN_TYPE: AZCLI
        run: azcopy copy 'dist/*' "https://azuresdkpartnerdrops.blob.core.windows.net/drops/azstoragetorch/python/$AZSTORAGETORCH_VERSION/" --recursive
